# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(acrName).azurecr.io/$(imageName)'
        dockerfile: 'Dockerfile'
        containerRegistry: '44583c40-8022-44ee-b55f-f4213cf5a309'
        tags: '$(tag)'
