trigger:
- none

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: '44583c40-8022-44ee-b55f-f4213cf5a309'

    - script: |
        az acr login --name prabuaksregistry
      displayName: 'Login to Azure Container Registry'

    - script: |
        docker run --privileged --rm tonistiigi/binfmt --install arm64
      displayName: 'Enable QEMU for ARM64'

    - script: |
        docker buildx create --name mybuilder --driver docker-container --use
        docker buildx inspect --bootstrap
      displayName: 'Set Up Docker Buildx'

    - script: |
        docker buildx build --platform linux/arm64 \
          -t prabuaksregistry.azurecr.io/apache:$(tag) \
          --push .
      displayName: 'Build and Push ARM64 Image'
