resources:
  pipelines:
    - pipeline: CI_Pipeline
      source: 'Build'
      trigger:
        branches:
          include:
            - add_helm

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'prabuaksregistry'
  imageName: 'apache'
  imageTag: '72'
  aksCluster: 'prabu-aks'
  helmChartPath: 'helm/'

steps:
  # Step1: Install Helm on the Pipeline Agent
  - task: HelmInstaller@0
    inputs:
      helmVersion: 'latest'

  # Step 2: Deploy to AKS using Helm
  - task: HelmDeploy@0
    inputs:
      azureSubscription: 'AKS-Service-Connection'
      azureResourceGroup: 'AKS-CLUSTER1'
      kubernetesCluster: '$(aksCluster)'
      namespace: 'default'
      command: 'install'
      chartType: 'FilePath'
      chartPath: '$(helmChartPath)'
      releaseName: 'app_apache'


