trigger:
  - none  
pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'prabuaksregistry'
  imageName: 'my-app'
  imageTag: '$(Build.BuildId)'
  aksCluster: 'MyAKSCluster'
  helmChartPath: 'helm/'

steps:
  # Step1: Install Helm on the Pipeline Agent
  - task: HelmInstaller@0
    inputs:
      helmVersion: 'latest'

  # Step 2: Deploy to AKS using Helm
  - task: HelmDeploy@0
    inputs:
      azureSubscription: 'AKS_cluster connection'
      azureResourceGroup: 'MyResourceGroup'
      kubernetesCluster: '$(aksCluster)'
      namespace: 'default'
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: '$(helmChartPath)'
      releaseName: 'my-app'
      arguments: >
        --set image.repository=$(acrName).azurecr.io/$(imageName)
        --set image.tag=$(imageTag)
