parameters:
  - name: helm_command
    type: string
    default: "my-release"
    values:
      - install
      - upgrade
    displayName: choose helm command
    description: for 1st time deployment only choose  install

trigger:
- none
pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'prabuaksregistry'
  imageName: 'apache'
  imageTag: 'latest'
  aksCluster: 'prabu-aks'
  helmChartPath: 'helm/'

steps:
  # Step1: Install Helm on the Pipeline Agent
  - task: HelmInstaller@0
    inputs:
      helmVersion: 'latest'

  # Step 2: Deploy to AKS using Helm
  - task: HelmDeploy@0
    inputs:
      azureSubscription: 'AKS-Service-Connection'
      azureResourceGroup: 'AKS-CLUSTER1'
      kubernetesCluster: '$(aksCluster)'
      namespace: 'default'
      command: '${{ parameters.helm_command }}'
      chartType: 'FilePath'
      chartPath: '$(helmChartPath)'
      releaseName: 'httpd'


