parameters:
  - name: ReleaseName
    type: string
    default: "my-release"

trigger:
- none

stages:
- stage: delete
  displayName: Delete failed deployment
  jobs:
  - job: cleanup
    displayName: Uninstall Helm deployment
    steps:
    - task: HelmDeploy@0
      inputs:
        azureSubscription: 'AKS-Service-Connection'
        azureResourceGroup: 'AKS-CLUSTER1'
        kubernetesCluster: '$(aksCluster)'
        namespace: 'default'
        command: 'uninstall'
        chartType: 'FilePath'
        chartPath: '$(helmChartPath)'
        releaseName: 'httpd'
